apiVersion: v1
kind: Pod
metadata:
  name: device-injection-demo
  annotations:
    devices.nri.io/container.null-dev: |
      - path: /dev/null-dev
        type: c
        major: 1
        minor: 3
    devices.nri.io/container.zero-dev: |
      - path: /dev/zero-dev
        type: c
        major: 1
        minor: 5
    devices.nri.io/container.null-zero-dev: |
      - path: /dev/null-dev
        type: c
        major: 1
        minor: 3
      - path: /dev/zero-dev
        type: c
        major: 1
        minor: 5
spec:
  containers:
  - name: null-dev
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - echo null-dev $(sleep inf)
    resources:
      requests:
        cpu: 100m
        memory: '100M'
      limits:
        cpu: 100m
        memory: '100M'
  - name: zero-dev
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - echo zero-dev $(sleep inf)
    resources:
      requests:
        cpu: 100m
        memory: '100M'
      limits:
        cpu: 100m
        memory: '100M'
  - name: null-zero-dev
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - echo null-zero-dev $(sleep inf)
    resources:
      requests:
        cpu: 100m
        memory: '100M'
      limits:
        cpu: 100m
        memory: '100M'
  terminationGracePeriodSeconds: 1
